/*
 * This source file was generated by the Gradle 'init' task
 */
package com.stack_demo;

import java.util.Arrays;
import java.util.Random;
import java.util.Stack;

class Dog implements Mammal {
    // Dog provides its own speak() implementation
    public void speak() {
        System.out.println("Woof! Woof!");
    }
}

class Cat implements Mammal {
    // Cat provides its own speak() implementation
    public void speak() {
        System.out.println("Meow! Meow!");
    }
}

class MuteKoala implements Mammal {
    // mute koala is mute is no speak() implementation :(
}

public class App {
    /**
     * Default method used in Junit tests to make sure the suite is working correctly.
     * @return Simple string for validation
    */
    public static String getGreeting() {
        return "Hello World!";
    }

    /**
     * Makes a sound for each animal in a Stack if not empty.
     * WARNING: It empties the stack in the process!
     * @param pets Stack of Mammal objects
     */
    public static void annoyNeighbors(Stack<? extends Mammal> pets) {
        while (!pets.empty()) {
            Mammal animal = pets.pop();
            animal.speak();
        }
    }

    /**
     * Static method to print out elements of a Stack one-by-one.
     * @param stack Stack to print
    */
    public static void printStack(Stack<?> stack) {
        System.out.println("Printing stack:");
        while (!stack.empty()) {
            System.out.print(stack.pop() + " ");
        }
        System.out.println();
    }

    /**
     * Creates and populates a small int Stack.
     * @return a populated int Stack
     */
    public static Stack<Integer> createIntStack(int size, int maxValue) {
        Stack<Integer> intStack = new Stack<Integer>(); 

        Random randGen = new Random();

        // add items
        for (int i = 0; i < 5; i++) {
            intStack.push(randGen.nextInt(maxValue));
        }

        return intStack;
    }

    /**
     * Creates and populates a small String Stack.
     * @return a populated string Stack
     */
    public static Stack<String> createStringStack() {
        Stack<String> stringStack = new Stack<String>();
        stringStack.push("piggy");
        stringStack.push("sofa");
        stringStack.push("peas");
        stringStack.push("umbrella");

        return stringStack;
    }

    public static Stack<Mammal> createMammalStack() {
        Stack<Mammal> pets = new Stack<Mammal>();
        pets.push(new Dog());
        pets.push(new Cat());
        pets.push(new MuteKoala());

        return pets;
    }

    public static void main(String[] args) {
        System.out.println(App.getGreeting());

        // create and print int Stack
        Stack<Integer> intStack = App.createIntStack(5, 100);
        App.printStack(intStack);

        // create and print a String Stack
        Stack<String> stringStack = App.createStringStack();
        App.printStack(stringStack);

        // create and print an animal Stack
        Stack<Mammal> mammalStack = App.createMammalStack();
        App.annoyNeighbors(mammalStack);
    }
}
